// Exports a list of canvas frame images as a GIF only.
//
// SELF-CONTAINED. No imports from sibling export files - the
// filename sanitiser below is local on purpose, so this file can be
// added or removed without touching the others.
//
// DEPENDENCY: gif.js, loaded DYNAMICALLY on first export rather than
// at module load. Two reasons:
//   1. Isolation. A static import means a gif.js load failure breaks
//      every module that imports this file - an export panel would
//      lose PNG and WebM too, for a problem in the least important
//      exporter.
//   2. Weight. gif.js plus its worker is real bundle size on a
//      phone, and most sessions never export a GIF.
// It must still be in package.json dependencies.
//
// ASYNC, RETURNS A BOOLEAN, matching exportPNG and exportWebM.
//     const ok = await exportGIF(images, 12, "loop.gif", onProgress);
//
// NEVER rejects - read lastGifExportError() for a reason to show on
// screen. Check lastGifExportWarning() even on success.
//
// FLATTEN ONTO AN OPAQUE BACKGROUND BEFORE CALLING. This is the
// thing that will otherwise ruin every export.
//
// gif.js discards alpha: a transparent canvas pixel is written as
// BLACK, not as transparent. A drawing on an empty canvas exports as
// your artwork on a solid black rectangle. Draw each frame onto a
// canvas pre-filled with white (or whatever the app shows behind the
// artwork) and pass that. This file does not draw and cannot do it
// for you.
//
// INPUT: pass CANVAS ELEMENTS. gif.js also accepts ImageData, but on
// that branch it takes the pixel buffer BY REFERENCE and silently
// ignores copy: true, so reusing one ImageData object across frames
// produces a GIF where every frame is identical. A 2D context works
// too. <img> elements are not reliably supported.
//
// ALL FRAMES MUST BE THE SAME SIZE. gif.js takes the output
// dimensions from the first frame and writes later frames into that
// grid regardless; a mismatch produces garbage rows with no error.
//
// GIF IS THE WORST OF THE THREE EXPORTS, by some distance:
//   - 256 colours per frame, so gradients and soft brushes band
//   - no usable transparency here - see the flatten note above
//   - files several times larger than the equivalent WebM
//   - pure CPU, no hardware acceleration, seconds to minutes
//   - frame rate capped far below playback (see GIF_MAX_FPS)
// Offer it for compatibility, not quality. WebM is better whenever
// the target supports it.
//
// NO CANCELLATION. Once started, a 60-frame encode runs to
// completion or to the timeout - minutes, with two workers busy. If
// the user leaves the export screen, the workers keep going. Adding
// cancellation means returning a handle instead of a boolean, which
// would break the shape shared with exportPNG and exportWebM.
//
// PASS onProgress. Encoding blocks long enough that the app looks
// frozen without it.

// Every frame's pixels are held in memory until render() finishes.
// At 800x600 that is ~2MB per frame, so 60 frames is ~115MB held at
// once - and the caller is holding its own rendered frames too. This
// cap is at the tab-kill threshold, not comfortably below it. Lower
// it before raising it.
const MAX_GIF_FRAMES = 60;

// GIF stores frame delay in CENTISECONDS, and browsers clamp any
// delay under ~20ms to 100ms. So a 60fps request becomes a 17ms
// delay, gets clamped, and the GIF plays at 10fps - slower than a
// 20fps request would. The playback FPS_MAX of 60 is NOT safe here.
// 20fps (50ms) is the highest rate that survives.
const GIF_MAX_FPS = 20;

// gif.js "quality" is a pixel SAMPLING INTERVAL, not a 0-10 scale:
// lower means sample more pixels, better colour, slower. 10 is the
// library default and a reasonable phone compromise.
const SAMPLE_INTERVAL = 10;

// Error-diffusion dithering. Off by default in gif.js. With only 256
// colours, soft brush gradients band badly, so this is a real
// quality win on hand-drawn art.
//
// BUT it is a per-pixel pass that measurably lengthens encoding, and
// the timeout below is fixed. If long exports start timing out, set
// this to false before raising MAX_GIF_FRAMES or the timeout.
const DITHER = "FloydSteinberg";

// Two workers suits a phone. More contend for the same cores.
const WORKER_COUNT = 2;

// gif.js has NO error event. A worker that fails to load, throws, or
// is blocked emits nothing at all - "finished" never fires, "abort"
// never fires, and the promise hangs forever with the button dead.
// Generous, since a 60-frame dithered encode legitimately takes
// minutes.
const ENCODE_TIMEOUT_MS = 300000;

// Object URLs are revoked after this long. Revoking immediately can
// cancel a download that has not started reading yet.
const REVOKE_DELAY_MS = 60000;

let gifExportError = "";
export function lastGifExportError() {
  return gifExportError;
  }

  // Set when the export SUCCEEDED but the result is not what was
  // asked for. Cleared at the start of every call.
  let gifExportWarning = "";
  export function lastGifExportWarning() {
    return gifExportWarning;
    }

    // A slash is the real hazard: a project title like "frame 1/2" is
    // read as a path by the OS. Leading dots make a hidden file. The
    // .gif extension is forced, since an extensionless download will
    // not open on some systems.
    function gifFilename(filename) {
      const raw = typeof filename === "string" ? filename.trim() : "";
        const cleaned = raw.replace(/[\\/:*?"<>|]/g, "-").replace(/^\.+/, "");
          const base = cleaned || "animation";
            return /\.gif$/i.test(base) ? base : `${base}.gif`;
            }

            // Canvas elements and ImageData expose width/height directly. A 2D
            // context does not - its size lives on ctx.canvas - so unwrap it
            // rather than rejecting input gif.js accepts.
            function frameSize(image) {
              const source = image?.canvas ?? image;
                const w = source?.width;
                  const h = source?.height;
                    return Number.isFinite(w) && Number.isFinite(h) && w > 0 && h > 0 ? { w, h } : null;
                    }

                    export async function exportGIF(frameImages, fps, filename = "animation.gif", onProgress) {
                      gifExportWarning = "";

                        if (!Array.isArray(frameImages) || frameImages.length === 0) {
                            gifExportError = "No frames to export";
                                return false;
                                  }
                                    if (!Number.isFinite(fps) || fps <= 0) {
                                        gifExportError = "Invalid frame rate";
                                            return false;
                                              }

                                                // Filter BEFORE the cap check, so a padded array is not rejected
                                                  // while its real frame count is under the limit.
                                                    const usable = frameImages.filter(Boolean);
                                                      if (usable.length === 0) {
                                                          gifExportError = "No usable frames to export";
                                                              return false;
                                                                }
                                                                  if (usable.length > MAX_GIF_FRAMES) {
                                                                      gifExportError = `GIF export is limited to ${MAX_GIF_FRAMES} frames - use WebM for longer animations`;
                                                                          return false;
                                                                            }

                                                                              const size = frameSize(usable[0]);
                                                                                if (!size) {
                                                                                    gifExportError = "Frames have no usable size";
                                                                                        return false;
                                                                                          }
                                                                                            for (const image of usable) {
                                                                                                const current = frameSize(image);
                                                                                                    if (!current || current.w !== size.w || current.h !== size.h) {
                                                                                                          gifExportError = "All frames must be the same size for GIF export";
                                                                                                                return false;
                                                                                                                    }
                                                                                                                      }

                                                                                                                        const cappedFps = Math.min(GIF_MAX_FPS, fps);
                                                                                                                          if (fps > GIF_MAX_FPS) {
                                                                                                                              gifExportWarning = `GIF exported at ${GIF_MAX_FPS}fps - the format cannot go faster`;
                                                                                                                                }

                                                                                                                                  // 1000 / fps must be a usable integer delay. A NaN or Infinity
                                                                                                                                    // delay produces a GIF that never advances.
                                                                                                                                      const delay = Math.max(1, Math.round(1000 / cappedFps));

                                                                                                                                        // Loaded here, not at module top, so a gif.js failure stays inside
                                                                                                                                          // this function instead of breaking every file that imports it.
                                                                                                                                            //
                                                                                                                                              // The worker must resolve as an asset URL. Without ?url, gif.js
                                                                                                                                                // looks for gif.worker.js at a path that does not exist in a
                                                                                                                                                  // bundled build - encoding starts, "finished" never fires, and
                                                                                                                                                    // nothing downloads with no error anywhere. This is the single
                                                                                                                                                      // most likely reason a GIF export does nothing.
                                                                                                                                                        let GIF;
                                                                                                                                                          let gifWorkerUrl;
                                                                                                                                                            try {
                                                                                                                                                                const [lib, worker] = await Promise.all([
                                                                                                                                                                      import("gif.js"),
                                                                                                                                                                            import("gif.js/dist/gif.worker.js?url"),
                                                                                                                                                                                ]);
                                                                                                                                                                                    GIF = lib.default;
                                                                                                                                                                                        gifWorkerUrl = worker.default;
                                                                                                                                                                                          } catch {
                                                                                                                                                                                              gifExportError = "GIF support could not be loaded - try PNG or WebM";
                                                                                                                                                                                                  return false;
                                                                                                                                                                                                    }

                                                                                                                                                                                                      let blob;
                                                                                                                                                                                                        try {
                                                                                                                                                                                                            blob = await new Promise((resolve, reject) => {
                                                                                                                                                                                                                  const gif = new GIF({
                                                                                                                                                                                                                          workers: WORKER_COUNT,
                                                                                                                                                                                                                                  quality: SAMPLE_INTERVAL,
                                                                                                                                                                                                                                          workerScript: gifWorkerUrl,
                                                                                                                                                                                                                                                  width: size.w,
                                                                                                                                                                                                                                                          height: size.h,
                                                                                                                                                                                                                                                                  repeat: 0,
                                                                                                                                                                                                                                                                          dither: DITHER,
                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                      let timer = null;
                                                                                                                                                                                                                                                                                            let settled = false;

                                                                                                                                                                                                                                                                                                  // abort() releases the workers. Without it a failed or timed
                                                                                                                                                                                                                                                                                                        // out encode leaves two workers grinding on a result nobody
                                                                                                                                                                                                                                                                                                              // will ever collect.
                                                                                                                                                                                                                                                                                                                    //
                                                                                                                                                                                                                                                                                                                          // The settled flag matters: abort() can re-emit the "abort"
                                                                                                                                                                                                                                                                                                                                // event, which would re-enter this through its own handler.
                                                                                                                                                                                                                                                                                                                                      const finish = (fn, value) => {
                                                                                                                                                                                                                                                                                                                                              if (settled) return;
                                                                                                                                                                                                                                                                                                                                                      settled = true;
                                                                                                                                                                                                                                                                                                                                                              clearTimeout(timer);
                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                if (gif.running) gif.abort();
                                                                                                                                                                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                                                                                                                                                                                  // Already stopped - nothing to release.
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                  fn(value);
                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                              gif.on("finished", (result) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (settled) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                              settled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      clearTimeout(timer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              resolve(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gif.on("abort", () => finish(reject, new Error("aborted")));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Wrapped, not passed straight through. This runs INSIDE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // gif.js's own loop, and gif.js has no error event - a throwing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // callback (an unmounted component's setState, say) could stall
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // the encode until the timeout. A broken progress bar must not
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // break the export.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (typeof onProgress === "function") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gif.on("progress", (value) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onProgress(value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Progress reporting is cosmetic - never fatal.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timer = setTimeout(() => finish(reject, new Error("timeout")), ENCODE_TIMEOUT_MS);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (const image of usable) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // copy: true on the CANVAS branch snapshots the pixels now.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Without it gif.js reads the source at render time, so a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // reused canvas makes every frame identical to the last
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // thing drawn - a GIF that looks like a still image.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              //
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // It has NO effect on the ImageData branch, which takes the
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // buffer by reference. See the input note in the header.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gif.addFrame(image, { delay, copy: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gif.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gifExportError =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  err?.message === "timeout"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "GIF encoding timed out - try fewer frames, or turn off dithering"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "Could not encode the GIF";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!blob || blob.size === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              gifExportError = "Encoding produced no image";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const url = URL.createObjectURL(blob);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const link = document.createElement("a");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                link.download = gifFilename(filename);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    link.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        link.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              URL.revokeObjectURL(url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gifExportError = "Could not start the download";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Must revoke, or the GIF blob is retained for the page's life.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => URL.revokeObjectURL(url), REVOKE_DELAY_MS);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              gifExportError = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }