import { pickVideoMimeType } from "./pickVideoMimeType.js";
import { safeFilename } from "./safeFilename.js";
import { FPS_MAX } from "../playback/fps.js";

// Records a sequence of canvas frames into a WebM video only.
//
// CHECK THE FPS_MAX IMPORT PATH against your tree. The fps module was
// reviewed as fps.js but playAction.js imports it from
// ../timeline/fpsSetting.js - one of those is wrong. Cloudflare Pages
// builds on Linux and 404s where a phone preview resolves fine.
//
// ASYNC, RETURNS A BOOLEAN.
//     const ok = await exportWebM(canvas, 12, 5000);
//
// Resolves true if the download was TRIGGERED, false otherwise.
// NEVER rejects - read lastVideoExportError() for a reason to show
// on screen, since there is no console on a phone.
//
// ALSO CHECK lastVideoExportWarning() ON SUCCESS. A true return can
// still mean a partial recording - see the grace path below.
//
// true does NOT guarantee a file was saved. link.click() returns
// normally even when the browser refuses the download or navigates
// instead. Same limitation as exportPNG.
//
// CALLER OBLIGATION - THE IMPORTANT ONE. This records whatever the
// canvas SHOWS for durationMs. It does not advance frames. Start
// playback BEFORE calling and stop it after, or the video is one
// still frame held for the whole duration:
//
//     const stop = playAction(advance);
//     const ok = await exportWebM(canvas, fps, durationMs);
//     stopAction(stop);
//
// durationMs must match the animation length: frameCount * (1000 /
// fps) for one loop. Longer records repeated loops; shorter cuts off.
//
// SECOND CALLER OBLIGATION: keep the screen awake and the app in the
// foreground for the whole recording. Backgrounding the tab pauses
// requestAnimationFrame, so playback stops advancing and the rest of
// the video is a held frame.
//
// RECORDS WHAT THIS CANVAS ELEMENT SHOWS. If layers render to
// separate canvases, composite them onto one canvas first - this
// file does not know about layers.
//
// iOS CAVEAT: MediaRecorder WebM support on Safari is partial and
// version-dependent, and the download attribute may be ignored.
// VERIFY ON YOUR OWN PHONE. If WebM is unsupported, the fallback is
// exporting a PNG sequence and assembling it elsewhere - that
// belongs in its own file, not a branch here.

// Emit a chunk this often rather than one buffer at the end, so a
// stop that never delivers still leaves usable data.
const CHUNK_INTERVAL_MS = 1000;

// Object URLs are revoked after this long. Revoking immediately can
// cancel a download that has not started reading yet.
const REVOKE_DELAY_MS = 60000;

// Grace period after the requested duration before giving up on
// onstop. Backgrounding the tab mid-recording can leave onstop
// unfired - without this the promise never settles, the capture
// track stays live, and export is dead until reload.
const STOP_GRACE_MS = 10000;

let videoExportError = "";
export function lastVideoExportError() {
  return videoExportError;
  }

  // Set when the export SUCCEEDED but the result may be imperfect.
  // Cleared at the start of every call. Separate from the error string
  // so a caller can show a "saved, but check it" message rather than
  // treating a partial file as a clean export.
  let videoExportWarning = "";
  export function lastVideoExportWarning() {
    return videoExportWarning;
    }

    export async function exportWebM(canvasElement, fps, durationMs, filename = "animation.webm") {
      videoExportWarning = "";

        if (!canvasElement || typeof canvasElement.captureStream !== "function") {
            videoExportError = "This browser cannot record the canvas";
                return false;
                  }
                    if (!Number.isFinite(fps) || fps <= 0) {
                        videoExportError = "Invalid frame rate";
                            return false;
                              }
                                if (!Number.isFinite(durationMs) || durationMs <= 0) {
                                    videoExportError = "Invalid duration";
                                        return false;
                                          }

                                            const mimeType = pickVideoMimeType();
                                              if (!mimeType) {
                                                  videoExportError = "This browser cannot record WebM video";
                                                      return false;
                                                        }

                                                          // Shares the playback ceiling rather than restating 60 here. One
                                                            // concept, one constant.
                                                              const captureFps = Math.min(FPS_MAX, fps);

                                                                let stream;
                                                                  try {
                                                                      // Throws SecurityError if the canvas is tainted by a
                                                                          // cross-origin image.
                                                                              stream = canvasElement.captureStream(captureFps);
                                                                                } catch {
                                                                                    videoExportError = "Could not capture the canvas";
                                                                                        return false;
                                                                                          }

                                                                                            let blob;
                                                                                              let failure = "";

                                                                                                try {
                                                                                                    blob = await new Promise((resolve, reject) => {
                                                                                                          let recorder;
                                                                                                                const chunks = [];
                                                                                                                      let stopTimer = null;
                                                                                                                            let graceTimer = null;

                                                                                                                                  // Both timers cleared on every exit, or an early failure leaves
                                                                                                                                        // them pending for the full remaining duration.
                                                                                                                                              const clearTimers = () => {
                                                                                                                                                      clearTimeout(stopTimer);
                                                                                                                                                              clearTimeout(graceTimer);
                                                                                                                                                                    };

                                                                                                                                                                          try {
                                                                                                                                                                                  recorder = new MediaRecorder(stream, { mimeType });
                                                                                                                                                                                        } catch {
                                                                                                                                                                                                failure = "This device rejected the video format";
                                                                                                                                                                                                        reject(new Error("construct"));
                                                                                                                                                                                                                return;
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                            recorder.ondataavailable = (e) => {
                                                                                                                                                                                                                                    if (e.data && e.data.size > 0) chunks.push(e.data);
                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                recorder.onerror = (e) => {
                                                                                                                                                                                                                                                        clearTimers();
                                                                                                                                                                                                                                                                // Keep the browser's own reason where there is one - a
                                                                                                                                                                                                                                                                        // generic string loses the only diagnostic available here.
                                                                                                                                                                                                                                                                                failure = e?.error?.name
                                                                                                                                                                                                                                                                                          ? `The recorder stopped: ${e.error.name}`
                                                                                                                                                                                                                                                                                                    : "The recorder stopped unexpectedly";
                                                                                                                                                                                                                                                                                                            reject(new Error("recorder"));
                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                        recorder.onstop = () => {
                                                                                                                                                                                                                                                                                                                                clearTimers();
                                                                                                                                                                                                                                                                                                                                        resolve(new Blob(chunks, { type: mimeType }));
                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                    recorder.start(CHUNK_INTERVAL_MS);

                                                                                                                                                                                                                                                                                                                                                          stopTimer = setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                  // Guard against a recorder already stopped by an error.
                                                                                                                                                                                                                                                                                                                                                                          if (recorder.state !== "inactive") recorder.stop();
                                                                                                                                                                                                                                                                                                                                                                                }, durationMs);

                                                                                                                                                                                                                                                                                                                                                                                      // onstop never arrived - most likely the tab was backgrounded.
                                                                                                                                                                                                                                                                                                                                                                                            // Salvage the chunks the timeslice already delivered rather
                                                                                                                                                                                                                                                                                                                                                                                                  // than hanging forever.
                                                                                                                                                                                                                                                                                                                                                                                                        //
                                                                                                                                                                                                                                                                                                                                                                                                              // The result is NOT guaranteed playable: a WebM whose final
                                                                                                                                                                                                                                                                                                                                                                                                                    // chunk never arrived may be truncated. Warn rather than
                                                                                                                                                                                                                                                                                                                                                                                                                          // reporting a clean export.
                                                                                                                                                                                                                                                                                                                                                                                                                                graceTimer = setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        clearTimers();

                                                                                                                                                                                                                                                                                                                                                                                                                                                // Stop explicitly instead of relying on the finally block
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // killing the tracks to shut the recorder down indirectly.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (recorder.state !== "inactive") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      recorder.stop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Already stopping - nothing to do.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (chunks.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                videoExportWarning =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Recording was cut short - the video may be incomplete or may not play";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resolve(new Blob(chunks, { type: mimeType }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        failure = "Recording timed out with no video";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reject(new Error("timeout"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, durationMs + STOP_GRACE_MS);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          videoExportError = failure || "Recording failed";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Release the capture track either way, or the canvas keeps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // feeding a stream nobody reads.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stream.getTracks().forEach((track) => track.stop());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!blob || blob.size === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    videoExportError = "Recording produced no video";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const url = URL.createObjectURL(blob);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const link = document.createElement("a");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      link.download = safeFilename(filename, "webm");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          link.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              link.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    URL.revokeObjectURL(url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        videoExportError = "Could not start the download";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Must revoke, or the video blob is retained for the page's life.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(() => URL.revokeObjectURL(url), REVOKE_DELAY_MS);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    videoExportError = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }